version: "3.3"
services:

  pgadmin:
    ports:
      - "5050:5050"

  backend:
    ports:
      - "8080:80"
    volumes:
      - ./backend/app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: bash -c "while true; do sleep 1; done"  # Infinite loop to keep container live doing nothing
    command: /start-reload.sh

networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
